import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import NavBar from "./NavBar";
import { Flex, Box } from "@radix-ui/themes";
import Footer from "./Footer";
import AdminShell from "./AdminShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="p-5">
          <Providers>
            <Providers>
              <AdminShell>{children}</AdminShell>
            </Providers>
          </Providers>
        </main>
      </body>
    </html>
  );
}
