import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import NavBar from "./NavBar";
import { Flex, Box } from "@radix-ui/themes";
import Footer from "./Footer";
import AdminShell from "./AdminShell";
import { isDatabaseConnected } from "@/lib/dbHealth";
import Maintenance from "./Maintenance";
import MaintenanceBanner from "./MaintenanceBanner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

const maintenanceMode = process.env.MAINTENANCE_MODE === "true";

  if (maintenanceMode) {
    return (
      <html lang="en">
        <body>
          <Maintenance/>
        </body>
      </html>
    );
  }



  const connected = await isDatabaseConnected();

  if (!connected) {
    return (
      <html lang="en">
        <body className="flex items-center justify-center h-screen bg-gray-100">
          <div className="bg-white p-10 rounded-xl shadow-lg text-center">
            <h1 className="text-3xl font-bold text-red-600">
              Database Not Running
            </h1>
            <p className="mt-4 text-gray-600">
              Please start MySQL on localhost:3307
            </p>
          </div>
        </body>
      </html>
    );
  }



  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MaintenanceBanner/>
        <main className="p-5">
          <Providers>
            <Providers>
              <AdminShell>{children}</AdminShell>
            </Providers>
          </Providers>
        </main>
      </body>
    </html>
  );
}
